import React from 'react';

import { useNavigate } from 'react-router';

import { Box, IconButton, List, Popover, styled } from '@mui/material';
import MoreVertIcon from '@mui/icons-material/MoreVert';

import { SidebarProps } from '../Sidebar/Sidebar.model';
import { SidebarItem } from '../SidebarItem/SidebarItem';

const StyledBox = styled(Box)(() => ({
  flexShrink: 0,
  whiteSpace: 'nowrap',
  boxSizing: 'border-box',
}));

/**
 * React functional component that generates a user popover with a list of routes.
 * This function uses React state to manage the opening and closing of the popover.
 * Uses the 'useNavigate' hook from React Router to handle navigation between routes.
 *
 * @param {Object} props - The properties passed to the component.
 * @param {Array} props.routes - An array of objects representing the routes.
 * @param {string} props.currentPath - The current path. Used to highlight the current route in the popover.
 *
 * @returns {JSX.Element} A JSX element representing the user popover.
 *
 * @example
 * <UserPopover routes={userRoutes} currentPath="/home" />
 */
export const UserPopover: React.FC<SidebarProps> = ({
  routes = [],
  currentPath,
}) => {
  const [anchorPop, setAnchorPop] = React.useState<HTMLButtonElement | null>(
    null,
  );

  /**
   * Handles the click event on a button element, setting the current element as the anchor for the popover.
   *
   * @param {Readonly<React.MouseEvent<HTMLButtonElement>>} event - The mouse event generated by clicking a button element.
   * @returns {void} Returns nothing.
   * @example
   * buttonElement.addEventListener('click', (event) => handleClick(event));
   */
  const handleClick = (
    event: Readonly<React.MouseEvent<HTMLButtonElement>>,
  ) => {
    setAnchorPop(event.currentTarget);
  };

  const handleClose = () => {
    setAnchorPop(null);
  };

  const navigate = useNavigate();

  const open = Boolean(anchorPop);

  // Filter routes that should not be shown in sidebar (legacy support)
  const popoverRoutes = routes.filter(route => route.showInSidebar === false);

  return (
    <>
      <IconButton onClick={handleClick}>
        <MoreVertIcon />
      </IconButton>
      <Popover
        open={open}
        anchorEl={anchorPop}
        onClose={handleClose}
        anchorOrigin={{
          vertical: 'center',
          horizontal: 'right',
        }}
      >
        <StyledBox>
          <List
            sx={{
              display: 'flex',
              flexDirection: 'column',
              height: '100%',
              padding: 0,
            }}
          >
            {popoverRoutes.map(({ linkTo, path, label, icon, id }, index) => (
              <SidebarItem
                key={id || index}
                path={path}
                text={label}
                selected={path === currentPath}
                open={open}
                icon={icon}
                {...(linkTo && {
                  onClick: () => {
                    navigate(linkTo.to, linkTo.options);
                  },
                })}
              />
            ))}
          </List>
        </StyledBox>
      </Popover>
    </>
  );
};
