rules: []
rulesConfigs: []
pages: []
resourceServers: []
clients:
  - name: Activity-tracker
    allowed_clients: []
    allowed_logout_urls:
      - http://localhost:4000
      - https://dev1.pette.dev
    allowed_origins:
      - http://localhost:4000
      - https://dev1.pette.dev
    app_type: spa
    async_approval_notification_channels:
      - guardian-push
    callbacks:
      - http://localhost:4000/login/callback
      - https://dev1.pette.dev/login/callback
    client_aliases: []
    cross_origin_auth: false
    cross_origin_authentication: true
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: expiring
      leeway: 0
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins:
      - http://localhost:4000
      - https://dev1.pette.dev
  - name: BAAA-hub
    allowed_clients: []
    allowed_origins:
      - http://localhost:4000
      - https://dev1.pette.dev
    app_type: spa
    callbacks:
      - http://localhost:4000/login/callback
      - https://dev1.pette.dev/login/callback
    client_aliases: []
    cross_origin_auth: false
    cross_origin_authentication: true
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: expiring
      leeway: 0
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    skip_non_verifiable_callback_uri_confirmation_prompt: true
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins:
      - http://localhost:4000
      - https://dev1.pette.dev
  - name: Default App
    async_approval_notification_channels:
      - guardian-push
    callbacks: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      rotation_type: non-rotating
    sso_disabled: false
  - name: baaa-hub-m2m
    allowed_clients: []
    app_type: non_interactive
    callbacks: []
    client_aliases: []
    cross_origin_auth: false
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
databases:
  - name: Username-Password-Authentication
    strategy: auth0
    authentication:
      active: true
    connected_accounts:
      active: false
    enabled_clients:
      - Activity-tracker
      - BAAA-hub
      - baaa-hub-m2m
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      passwordPolicy: good
      passkey_options:
        challenge_ui: both
        local_enrollment_enabled: true
        progressive_enrollment_enabled: true
      strategy_version: 2
      authentication_methods:
        passkey:
          enabled: false
        password:
          enabled: true
      brute_force_protection: true
    realms:
      - Username-Password-Authentication
connections:
  - name: google-oauth2
    strategy: google-oauth2
    authentication:
      active: true
    connected_accounts:
      active: false
    enabled_clients:
      - BAAA-hub
      - baaa-hub-m2m
      - Default App
    is_domain_connection: false
    options:
      email: true
      scope:
        - email
        - profile
      profile: true
tenant:
  enabled_locales:
    - en
  flags:
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  oidc_logout:
    rp_logout_end_session_endpoint_discovery: true
  resource_parameter_profile: audience
  sandbox_version: '22'
emailProvider: {}
emailTemplates: []
clientGrants: []
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: false
  - name: push-notification
    enabled: false
  - name: recovery-code
    enabled: false
  - name: sms
    enabled: false
  - name: webauthn-platform
    enabled: false
  - name: webauthn-roaming
    enabled: false
guardianPolicies:
  policies: []
guardianPhoneFactorMessageTypes:
  message_types: []
roles: []
branding:
  templates: []
phoneProviders: []
prompts:
  customText: {}
  partials: {}
  screenRenderers: []
  universal_login_experience: new
actions:
  - name: Sync User to Database
    code: ./actions/Sync User to Database/code.js
    dependencies:
      - name: abort-controller
        version: 3.0.0
      - name: node-fetch
        version: 2.6.12
    deployed: true
    runtime: node18
    secrets: []
    status: built
    supported_triggers:
      - id: post-login
        version: v3
triggers:
  post-login:
    - action_name: Sync User to Database
      display_name: Sync User to Database
organizations: []
attackProtection:
  botDetection:
    challenge_password_policy: never
    challenge_passwordless_policy: never
    challenge_password_reset_policy: never
    allowlist: []
    bot_detection_level: medium
    monitoring_mode_enabled: false
  breachedPasswordDetection:
    enabled: false
    shields: []
    admin_notification_frequency: []
    method: standard
    stage:
      pre-user-registration:
        shields: []
      pre-change-password:
        shields: []
  bruteForceProtection:
    enabled: true
    shields:
      - block
      - user_notification
    mode: count_per_identifier_and_ip
    allowlist: []
    max_attempts: 10
  captcha:
    active_provider_id: auth_challenge
    simple_captcha: {}
    auth_challenge:
      fail_open: false
    recaptcha_v2:
      site_key: ''
      secret: '##CAPTCHA_RECAPTCHA_V2_SECRET##'
    recaptcha_enterprise:
      site_key: ''
      project_id: '##CAPTCHA_RECAPTCHA_ENTERPRISE_PROJECT_ID##'
      api_key: '##CAPTCHA_RECAPTCHA_ENTERPRISE_API_KEY##'
    hcaptcha:
      site_key: ''
      secret: '##CAPTCHA_HCAPTCHA_SECRET##'
    friendly_captcha:
      site_key: ''
      secret: '##CAPTCHA_FRIENDLY_CAPTCHA_SECRET##'
    arkose:
      site_key: ''
      client_subdomain: client-api
      verify_subdomain: verify-api
      fail_open: false
      secret: '##CAPTCHA_ARKOSE_SECRET##'
  suspiciousIpThrottling:
    enabled: true
    shields:
      - admin_notification
      - block
    allowlist: []
    stage:
      pre-login:
        max_attempts: 100
        rate: 864000
      pre-user-registration:
        max_attempts: 50
        rate: 1200
logStreams: []
customDomains: []
themes: []
forms: []
flows: []
flowVaultConnections: []
selfServiceProfiles: []
userAttributeProfiles: []
connectionProfiles: []
